import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  container: {
    padding: "16px",
    minWidth: "280px",
    fontFamily: "system-ui, sans-serif",
    fontSize: "14px",
  },
  title: {
    margin: "0 0 8px",
    fontSize: "16px",
    fontWeight: 600,
  },
  subtitle: {
    margin: "0 0 12px",
    color: "#6b7280",
    fontSize: "13px",
  },
  siteLoginButton: {
    width: "100%",
    marginBottom: "12px",
    padding: "10px 16px",
    fontSize: "14px",
    fontWeight: 500,
    color: "#3b82f6",
    backgroundColor: "transparent",
    border: "1px solid #93c5fd",
    borderRadius: "6px",
    cursor: "pointer",
  },
  loading: {
    margin: 0,
    color: "#6b7280",
  },
  successBadge: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    background: "#dcfce7",
    color: "#16a34a",
    fontSize: 20,
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 12px",
  },
  successMessage: {
    margin: "0 0 4px",
    fontSize: 14,
    color: "#16a34a",
    fontWeight: 500,
  },
  userEmail: {
    margin: "0 0 12px",
    fontWeight: 500,
    color: "#374151",
  },
  hint: {
    margin: "0 0 16px",
    color: "#6b7280",
    fontSize: "13px",
    lineHeight: 1.4,
  },
  logoutButton: {
    width: "100%",
    padding: "10px 16px",
    fontSize: "14px",
    color: "#dc2626",
    backgroundColor: "transparent",
    border: "1px solid #fca5a5",
    borderRadius: "6px",
    cursor: "pointer",
  },
  settingsButton: {
    width: "100%",
    padding: "10px 16px",
    fontSize: "14px",
    color: "#6b7280",
    backgroundColor: "transparent",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    cursor: "pointer",
  },
  formGroup: {
    marginBottom: "12px",
  },
  label: {
    display: "block",
    marginBottom: "4px",
    fontSize: "13px",
    fontWeight: 500,
    color: "#374151",
  },
  select: {
    width: "100%",
    padding: "8px 12px",
    fontSize: "14px",
    color: "#374151",
    backgroundColor: "#fff",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    cursor: "pointer",
  },
  version: {
    margin: "12px 0 0",
    fontSize: "11px",
    color: "#9ca3af",
    textAlign: "center" as const,
  },
  primaryButton: {
    width: "100%",
    marginBottom: "12px",
    padding: "10px 16px",
    fontSize: "14px",
    fontWeight: 500,
    color: "#fff",
    backgroundColor: "#2563eb",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
  },
  errorText: {
    margin: 0,
    marginTop: 8,
    color: "#dc2626",
    fontSize: "13px",
  },
};
