import { realtimeMiddleware } from "@bunworks/inngest-realtime/middleware";

import { EventSchemas, Inngest } from "inngest";
import {
  analyzeFreelanceResponseDataSchema,
  analyzeSingleResponseDataSchema,
  bufferFlushDataSchema,
  candidateOfferSendDataSchema,
  candidateWelcomeBatchDataSchema,
  candidateWelcomeDataSchema,
  checkAllPublicationStatusesDataSchema,
  checkPublicationStatusDataSchema,
  collectChatIdsDataSchema,
  conversationMessageReceivedDataSchema,
  conversationMessageSendDataSchema,
  generateInvitationDataSchema,
  gigImportByUrlDataSchema,
  gigImportNewDataSchema,
  gigRankingRecalculateDataSchema,
  gigRecommendationGenerateDataSchema,
  gigResponseEvaluateDataSchema,
  gigShortlistRecalculateDataSchema,
  gigSyncResponsesDataSchema,
  interviewAnalysisDataSchema,
  interviewCompleteDataSchema,
  interviewSendQuestionDataSchema,
  kworkChatImportHistoryDataSchema,
  kworkChatProcessDataSchema,
  messageBufferedDataSchema,
  parseFreelanceProfileDataSchema,
  parseNewResumesDataSchema,
  parseSingleResumeDataSchema,
  recommendationGenerateDataSchema,
  refreshAllResumesDataSchema,
  refreshSingleResumeDataSchema,
  responseScreenDataSchema,
  screenAllResponsesDataSchema,
  screenNewResponsesDataSchema,
  screenResponsesBatchDataSchema,
  sendFreelanceNotificationDataSchema,
  syncArchivedVacancyResponsesDataSchema,
  telegramAuthErrorDataSchema,
  telegramUnidentifiedMessageSendDataSchema,
  typingActivityDataSchema,
  vacancyFetchActiveListDataSchema,
  vacancyFetchArchivedListDataSchema,
  vacancyImportArchivedDataSchema,
  vacancyImportArchivedSelectedDataSchema,
  vacancyImportByUrlDataSchema,
  vacancyImportNewDataSchema,
  vacancyImportNewSelectedDataSchema,
  vacancyRecommendationGenerateDataSchema,
  vacancyRequirementsExtractDataSchema,
  vacancyResponsesRefreshDataSchema,
  vacancyUpdateActiveDataSchema,
  vacancyUpdateSingleDataSchema,
  verifyHHCredentialsDataSchema,
  verifyKworkCredentialsDataSchema,
  voiceTranscriptionDataSchema,
} from "./types";

// Создание Inngest клиента с Zod схемами для типобезопасных событий
export const inngest = new Inngest({
  id: "qbs-autonaim",
  name: "QBS Автонайм Jobs",
  middleware: [realtimeMiddleware()],
  schemas: new EventSchemas().fromSchema({
    "vacancy/requirements.extract": vacancyRequirementsExtractDataSchema,
    "vacancy/responses.sync-archived": syncArchivedVacancyResponsesDataSchema,
    "vacancy/publications.status.check-all":
      checkAllPublicationStatusesDataSchema,
    "vacancy/publication.status.check": checkPublicationStatusDataSchema,
    "vacancy/import.new": vacancyImportNewDataSchema,
    "vacancy/import.archived": vacancyImportArchivedDataSchema,
    "vacancy/import.archived-selected": vacancyImportArchivedSelectedDataSchema,
    "vacancy/import.new-selected": vacancyImportNewSelectedDataSchema,
    "vacancy/import.by-url": vacancyImportByUrlDataSchema,
    "vacancy/fetch-active-list": vacancyFetchActiveListDataSchema,
    "vacancy/fetch-archived-list": vacancyFetchArchivedListDataSchema,
    "response/screen": responseScreenDataSchema,
    "response/screen.new": screenNewResponsesDataSchema,
    "response/screen.all": screenAllResponsesDataSchema,
    "response/analyze.single": analyzeSingleResponseDataSchema,
    "response/screen.batch": screenResponsesBatchDataSchema,
    "response/resume.parse-new": parseNewResumesDataSchema,
    "response/resume.parse-single": parseSingleResumeDataSchema,
    "response/resume.refresh": refreshSingleResumeDataSchema,
    "response/resume.refresh.all": refreshAllResumesDataSchema,
    "response/recommendation.generate": recommendationGenerateDataSchema,
    "response/vacancy-recommendation.generate":
      vacancyRecommendationGenerateDataSchema,
    "response/gig-recommendation.generate": gigRecommendationGenerateDataSchema,
    "vacancy/update.active": vacancyUpdateActiveDataSchema,
    "vacancy/update.single": vacancyUpdateSingleDataSchema,
    "vacancy/responses.refresh": vacancyResponsesRefreshDataSchema,
    "vacancy/chat-ids.collect": collectChatIdsDataSchema,
    "candidate/welcome": candidateWelcomeDataSchema,
    "candidate/welcome.batch": candidateWelcomeBatchDataSchema,
    "candidate/offer.send": candidateOfferSendDataSchema,
    "freelance/response.analyze": analyzeFreelanceResponseDataSchema,
    "freelance/invitation.generate": generateInvitationDataSchema,
    "freelance/notification.send": sendFreelanceNotificationDataSchema,
    "freelance/profile.parse": parseFreelanceProfileDataSchema,
    "telegram/message.received": conversationMessageReceivedDataSchema,
    "telegram/message.send": conversationMessageSendDataSchema,
    "telegram/message.send.by-username":
      telegramUnidentifiedMessageSendDataSchema,
    "telegram/voice.transcribe": voiceTranscriptionDataSchema,
    "telegram/interview.analyze": interviewAnalysisDataSchema,
    "telegram/interview.send-question": interviewSendQuestionDataSchema,
    "telegram/interview.complete": interviewCompleteDataSchema,
    "telegram/auth.error": telegramAuthErrorDataSchema,
    "integration/verify-hh-credentials": verifyHHCredentialsDataSchema,
    "integration/verify-kwork-credentials": verifyKworkCredentialsDataSchema,
    "interview/message.buffered": messageBufferedDataSchema,
    "interview/typing.activity": typingActivityDataSchema,
    "interview/buffer.flush": bufferFlushDataSchema,
    "web/interview.send-question": interviewSendQuestionDataSchema,
    "web/interview.complete": interviewCompleteDataSchema,
    "gig/import.new": gigImportNewDataSchema,
    "gig/import.by-url": gigImportByUrlDataSchema,
    "gig/ranking.recalculate": gigRankingRecalculateDataSchema,
    "gig/shortlist.recalculate": gigShortlistRecalculateDataSchema,
    "gig/response.evaluate": gigResponseEvaluateDataSchema,
    "gig/sync-responses": gigSyncResponsesDataSchema,
    "kwork-chat/process": kworkChatProcessDataSchema,
    "kwork-chat/import-history": kworkChatImportHistoryDataSchema,
  }),
});
