/**
 * Клиенты внешних API для интеграций
 * Лёгкий пакет без puppeteer/crawlee — только HTTP вызовы
 */

export {
  cookiesToHeaderString,
  createKworkApiClient,
  extractTokenFromSignInResponse,
  getDialog,
  getDialogs,
  getInboxMessage,
  getInboxTracks,
  getKworkDetails,
  getMyWants,
  getOffer,
  getOffers,
  getProject,
  getProjects,
  getUser,
  getWant,
  getWebAuthToken,
  isKworkAuthError,
  KWORK_ERROR_CODES,
  type KworkCredentials,
  type KworkDetails,
  type KworkErrorResponse,
  type KworkInboxMessage,
  type KworkInboxTracksParams,
  type KworkMyWantsParams,
  type KworkOffer,
  type KworkOffersParams,
  type KworkProject,
  type KworkProjectsParams,
  type KworkSignInParams,
  type KworkWantPayer,
  type KworkWebAuthTokenResponse,
  type KworkWebCookie,
  parseSetCookieToCookieHeader,
  parseSetCookieToCookies,
  sendMessage,
  signIn,
  type WebParsedOffer,
} from "./kwork/api";
