// candidates domain exports
export {
  ActivityTimeline,
  CandidateCard,
  CandidateColumn,
  CandidateInfo,
  CandidateKanbanCard,
  CandidateKanbanColumn,
  CandidateKanbanItem,
  CandidatePipeline,
  CandidatesTable,
  ChatSection,
  type ColumnVisibility,
  ColumnVisibilityToggle,
  CommentsSection,
  FactorBreakdown,
  type FunnelActivity,
  type FunnelCandidate,
  type FunnelCandidateDetail,
  type FunnelComment,
  type FunnelStage,
  MatchScoreCircle,
  MetaMatchSection,
  OverallAssessment,
  PipelineBoardView,
  PipelineToolbar,
  PipelineViewSwitcher,
  ScoreExplanation,
  STAGE_COLORS,
  STAGE_LABELS,
} from "./components";
